### ISSUE TITLE
Code block don't work

### ISSUE THREAD

**Issue by vialcollet** [andyyou/chrome-gpt-markdown#1]
Hi
Nice extenstion!
However, code blocks are not exported properly:
```
javascriptCopy code

``function h(html) {      return html         .replace(/<p>/g, '\n\n')         .replace(/<\/p>/g, '')         .replace(/<b>/g, '**')         .replace(/<\/b>/g, '**')         .replace(/<i>/g, '_')         .replace(/<\/i>/g, '_')         .replace(/<code[^>]*>/g, (match) => {       
```

As you can see, there is only two ` instead of 3 and the language is not writen. Also there is a missing line feed.

Here is what we should get in this ex:

```
```js
function h(html) {      return html         .replace(/<p>/g, '\n\n')         .replace(/<\/p>/g, '')         .replace(/<b>/g, '**')         .replace(/<\/b>/g, '**')         .replace(/<i>/g, '_')         .replace(/<\/i>/g, '_')         .replace(/<code[^>]*>/g, (match) => {       
````
```

**Comment by andyyou** [comment]
Sorry for reply late I just got your message. Yes you are right I will check why `turndown.js` convert that result. Thanks anyway.

**Comment by andyyou** [comment]
@vialcollet I fix the issue and publish on store and support light and dark mode as well. After you check the result I will close this issue. Thanks

**Comment by vialcollet** [comment]
Ouch... sorry I missed your message.  
Thanks a lot for the fix
